---
- name: Ожидание доступности серверов
  ansible.builtin.import_playbook: ./playbooks/_0_wait_for_connection.yaml

- name: Общие настройки серверов
  ansible.builtin.import_playbook: ./playbooks/_1_install_soft.yaml
