---

- name: Creating repository_fact
  ansible.builtin.set_fact:
    repository_fact:
      - "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: Install Docker.
  ansible.builtin.include_tasks: ./_0_utility/apt.yaml
  vars:
    gpg_key:
      - "https://download.docker.com/linux/ubuntu/gpg"
    repository: "{{ repository_fact }}"
    list:
      - 'apparmor'
      - 'apparmor-utils'
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'


- name: Check apparmor status ...
  ansible.builtin.shell: aa-status
  args:
    executable: /bin/bash
  register: aa_status
  ignore_errors: true

- name: And restart servers
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: aa_status.rc > 0

- name: Await
  ansible.builtin.wait_for_connection:
    timeout: 9000
